name: Live Transaction Monitoring

on: [push, pull_request]

jobs:
  Live_Transaction_Checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm ci

      - name: Run QRPH Deposit Transaction Checker
        run: npx cypress run --spec "cypress/e2e/TransactionChecker/Deposit/QRPH_DEPOSIT.cy.js"

      - name: Run Gcash Deposit Transaction Checker
        run: npx cypress run --spec "cypress/e2e/TransactionChecker/Deposit/GCASH_DEPOSIT.cy.js"

      - name: Run JPayout Deposit Transaction Checker
        run: npx cypress run --spec "cypress/e2e/TransactionChecker/Deposit/JPAY_DEPOSIT.cy.js"

      - name: Run LBTIDR Deposit Transaction Checker
        run: npx cypress run --spec "cypress/e2e/TransactionChecker/Deposit/LBTIDR_DEPOSIT.cy.js"

      - name: Run LBTTHB Deposit Transaction Checker
        run: npx cypress run --spec "cypress/e2e/TransactionChecker/Deposit/LBTTHB_DEPOSIT.cy.js"

      - name: Run JPay Withdrawal Transaction Checker
        run: npx cypress run --spec "cypress/e2e/TransactionChecker/Withdrawal/JPAY_WITHDRAWAL.cy.js"

      - name: Run Instapay Withdrawal Transaction Checker
        run: npx cypress run --spec "cypress/e2e/TransactionChecker/Withdrawal/INSTAPAY_WITHDRAWAL.cy.js"

      - name: Set Date Variable
        id: date
        run: echo "DATE=$(date +'%m/%d/%y')" >> $GITHUB_ENV

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Live_Transaction_Checker_${{github.env.DATE}}" # Name of the artifact/file with date
          path: cypress/e2e/Reports/LiveTransactionChecker/LiveTransactionChecker.xlsx

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-transaction-screenshots
          path: cypress/screenshots